# Generated by Django 2.0.2 on 2019-06-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('v1_sensor', models.CharField(max_length=255)),
                ('v2_sensor', models.CharField(max_length=255)),
                ('v3_sensor', models.CharField(max_length=255)),
                ('v4_sensor', models.CharField(max_length=255)),
            ],
        ),
    ]
